reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods

disabled_rules: # rule identifiers to exclude from running
    - trailing_whitespace
    - force_cast
    - force_unwrapping
    - force_try
    - line_length
    - identifier_name
    - function_body_length
    - large_tuple
    - file_length
    - comment_spacing
    - is_disjoint
    - multiple_closures_with_trailing_closure
    - legacy_constructor
